name: Send Google Chat Message

on:
  workflow_dispatch:  # you can also trigger on push, PR, etc.
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Google Chat
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"text": "Hello from GitHub Actions- test1 🚀"}' \
            "https://chat.googleapis.com/v1/spaces/AAQAu1PehHg/webhooks?key=${{ secrets.GCHAT_KEY }}&token=${{ secrets.GCHAT_TOKEN }}"
