name: Send Webhook on Push

on:
  push:
    branches:
      - main   # triggers only when pushing to main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"text":"Hello from GitHub Actions 🚀- on push to main"}' \
            "${{ secrets.WEBHOOK_URL }}"
